[24.066448212] 2018-06-27 12:53:33,858 - INFO - launcher: Starting sanity checks
[25.071620941] 2018-06-27 12:53:33,859 - INFO - launcher: Checking for Python 3.5+
[25.572061539] 2018-06-27 12:53:33,860 - INFO - launcher: Checking console encoding
[25.572061539] 2018-06-27 12:53:33,860 - INFO - launcher: Setting console encoding to UTF-8
[26.072740555] 2018-06-27 12:53:33,860 - INFO - launcher: Ensuring we're in the right environment
[28.078079224] 2018-06-27 12:53:33,862 - INFO - launcher: Adding local bins/ folder to path
[29.582262039] 2018-06-27 12:53:33,864 - INFO - launcher: Required checks passed.
[30.583858490] 2018-06-27 12:53:33,865 - INFO - launcher: Optional checks passed.
[30.583858490] 2018-06-27 12:53:33,865 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.1270790100097656] 2018-06-27 12:53:34,961 - WARNING - musicbot.config | In config.py::MainThread(2852), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.1270790100097656] 2018-06-27 12:53:34,961 - INFO - musicbot.config | In config.py::MainThread(2852), line 123 in run_checks: Using i18n: config/i18n/en.json
[1.1280817985534668] 2018-06-27 12:53:34,962 - WARNING - musicbot.config | In config.py::MainThread(2852), line 206 in create_empty_file_ifnoexist: Creating config/blacklist.txt
[1.1285834312438965] 2018-06-27 12:53:34,963 - WARNING - musicbot.config | In config.py::MainThread(2852), line 206 in create_empty_file_ifnoexist: Creating config/whitelist.txt
[1.1366062164306641] 2018-06-27 12:53:34,971 - DEBUG - musicbot.config | In config.py::MainThread(2852), line 291 in find_autoplaylist: Copying _autoplaylist.txt to autoplaylist.txt
[1.1371066570281982] 2018-06-27 12:53:34,971 - INFO - musicbot.permissions | In permissions.py::MainThread(2852), line 39 in __init__: Permissions file not found, copying example_permissions.ini
[1.1436254978179932] 2018-06-27 12:53:34,978 - DEBUG - musicbot.json | In json.py::MainThread(2852), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.3261227607727051] 2018-06-27 12:53:35,160 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 227 in _setup_logging: Set logging level to INFO
[1.3266243934631348] 2018-06-27 12:53:35,161 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 84 in __init__: Starting MusicBot 1.9.7
[1.3266243934631348] 2018-06-27 12:53:35,161 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 90 in __init__: Loaded autoplaylist with 2531 entries
[3.9406502246856689] 2018-06-27 12:53:37,775 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 1074 in on_ready: Connection established, ready to go.
[3.9406502246856689] 2018-06-27 12:53:37,775 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 339 in _cache_app_info: Caching app info
[4.0660445690155029] 2018-06-27 12:53:37,900 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 889 in _scheck_ensure_env: Ensuring data folders exist
[4.0785777568817139] 2018-06-27 12:53:37,913 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 905 in _scheck_server_permissions: Checking server permissions
[4.0790789127349854] 2018-06-27 12:53:37,913 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[4.0795805454254150] 2018-06-27 12:53:37,914 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 913 in _scheck_configs: Validating config
[4.0795805454254150] 2018-06-27 12:53:37,914 - DEBUG - musicbot.config | In config.py::MainThread(2852), line 212 in async_validate: Validating options...
[4.0795805454254150] 2018-06-27 12:53:37,914 - DEBUG - musicbot.bot | In bot.py::MainThread(2852), line 916 in _scheck_configs: Validating permissions config
[4.0800848007202148] 2018-06-27 12:53:37,914 - DEBUG - musicbot.permissions | In permissions.py::MainThread(2852), line 64 in async_validate: Validating permissions...
[4.0805838108062744] 2018-06-27 12:53:37,915 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1091 in on_ready: Connected: 461471585770012681/Gravity Networks#4646
[4.0820884704589844] 2018-06-27 12:53:37,916 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1099 in on_ready: Owner:     347343939478618113/_Moondust_#7800

[4.0830907821655273] 2018-06-27 12:53:37,917 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1102 in on_ready: Server List:
[4.0835916996002197] 2018-06-27 12:53:37,918 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1105 in on_ready:  - Moondust's Private Room
[4.0840954780578613] 2018-06-27 12:53:37,918 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1151 in on_ready: Not bound to any text channels
[4.0850954055786133] 2018-06-27 12:53:37,919 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 1177 in on_ready: Not autojoining any voice channels
[26.4913647174835205] 2018-06-27 12:54:00,325 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2852), line 2938 in on_voice_state_update: Voice state update for 347343939478618113/_Moondust_#7800 on Moondust's Private Room/General -> [CONNECT]
[34.6934580802917480] 2018-06-27 12:54:08,528 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2852), line 2938 in on_voice_state_update: Voice state update for 347343939478618113/_Moondust_#7800 on Moondust's Private Room/General -> [DISCONNECT]
[200.4023571014404297] 2018-06-27 12:56:54,236 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2852), line 2938 in on_voice_state_update: Voice state update for 347343939478618113/_Moondust_#7800 on Moondust's Private Room/General -> [CONNECT]
[209.3674354553222656] 2018-06-27 12:57:03,201 - INFO - musicbot.bot | In bot.py::MainThread(2852), line 2734 in on_message: 347343939478618113/_Moondust_#7800: !summon
